title: Erik Sprohge, Ph.D.
logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Please see my sample projects 
  <br><br>
  Second description 
  <br><br>
  <a href="https://https://www.linkedin.com/in/erik-sprohge-33532248/View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
